/**
 * rsbuild-plugin-css-purge
 *
 * Two-level CSS purge for @pathscale/ui consumers.
 *
 * Level 1: class-level purge via purgecss — removes entire rules whose selectors
 *          don't match the safelist built from consumer JSX analysis.
 * Level 2: attribute-level purge — within kept rules, strips compound selectors
 *          containing data-attr / aria-attr attribute selectors not in the attr safelist.
 *
 * Usage in rsbuild.config.ts:
 *   import { pluginCssPurge } from "@pathscale/rebuild-plugin-ui-css-purge";
 *   export default defineConfig({ plugins: [pluginCssPurge({ manifest: "..." })] });
 */

import type { RsbuildPlugin } from "@rsbuild/core";
import { PurgeCSS } from "purgecss";
import postcss from "postcss";
import type { Rule, AtRule } from "postcss";
import swc from "@swc/core";
import path from "path";
import { readFile as nodeReadFile } from "node:fs/promises";
import { glob as fastGlob } from "fast-glob";

// ── Types ─────────────────────────────────────────────────────────────────────

interface ComponentManifest {
  classes: {
    always: string[];
    byProp: Record<string, string[] | Record<string, string[]>>;
  };
  attrs?: Record<string, Record<string, string>>;
}

type PurgeManifest = Record<string, ComponentManifest>;

interface PropUsage {
  component: string;
  props: Map<string, string | "DYNAMIC">;
  booleanProps: Set<string>;
  hasSpread: boolean;
}

// ── Plugin options ─────────────────────────────────────────────────────────────

export interface CssPurgeOptions {
  /** Path to purge-manifest.json (generated by generate-manifest.ts) */
  manifest: string;
  /** Consumer source directory to scan for JSX usage (default: "src") */
  srcDir?: string;
  /** Enable Level 2 attribute purge (default: true) */
  attrPurge?: boolean;
  /** Enable CSS variable cleanup (default: true) */
  cleanVars?: boolean;
  /** Log purge stats (default: true) */
  verbose?: boolean;
}

// ── AST utilities ─────────────────────────────────────────────────────────────

function walkAST(node: any, visitor: (node: any) => void) {
  if (!node || typeof node !== "object") return;
  visitor(node);
  for (const key of Object.keys(node)) {
    if (key === "span") continue;
    const val = node[key];
    if (Array.isArray(val)) {
      for (const item of val) walkAST(item, visitor);
    } else if (val && typeof val === "object") {
      walkAST(val, visitor);
    }
  }
}

function extractUIImports(ast: any): Map<string, string> {
  const imports = new Map<string, string>();
  for (const node of ast.body) {
    if (node.type !== "ImportDeclaration") continue;
    const src = node.source?.value as string;
    if (!src || !src.startsWith("@pathscale/ui")) continue;
    for (const spec of node.specifiers) {
      if (spec.type === "ImportSpecifier") {
        const imported = spec.imported?.value ?? spec.local?.value;
        const local = spec.local?.value;
        if (local && imported) imports.set(local, imported);
      } else if (spec.type === "ImportDefaultSpecifier") {
        const local = spec.local?.value;
        if (local) imports.set(local, local);
      }
    }
  }
  return imports;
}

function extractJSXUsages(ast: any, uiComponents: Map<string, string>): PropUsage[] {
  const usages: PropUsage[] = [];
  walkAST(ast, (node) => {
    if (node.type !== "JSXOpeningElement") return;
    let elementName: string | null = null;
    let rootName: string | null = null;
    if (node.name?.type === "Identifier") {
      elementName = node.name.value;
      rootName = elementName;
    } else if (node.name?.type === "JSXMemberExpression") {
      const parts: string[] = [];
      let cursor = node.name;
      while (cursor?.type === "JSXMemberExpression") {
        parts.unshift(cursor.property?.value);
        cursor = cursor.object;
      }
      if (cursor?.type === "Identifier") {
        parts.unshift(cursor.value);
        rootName = cursor.value;
      }
      elementName = parts.join(".");
    }
    if (!rootName || !uiComponents.has(rootName)) return;
    const usage: PropUsage = {
      component: elementName!,
      props: new Map(),
      booleanProps: new Set(),
      hasSpread: false,
    };
    for (const attr of node.attributes || []) {
      if (attr.type === "SpreadElement" || attr.type === "JSXSpreadAttribute") {
        usage.hasSpread = true;
        continue;
      }
      if (attr.type !== "JSXAttribute") continue;
      const propName = attr.name?.value;
      if (!propName) continue;
      if (!attr.value) {
        usage.booleanProps.add(propName);
      } else if (attr.value.type === "StringLiteral") {
        usage.props.set(propName, attr.value.value);
      } else {
        usage.props.set(propName, "DYNAMIC");
      }
    }
    usages.push(usage);
  });
  return usages;
}

// ── Safelist builder ───────────────────────────────────────────────────────────

function buildSafelists(
  allUsages: PropUsage[],
  manifest: PurgeManifest,
): { classSafelist: Set<string>; attrSafelist: Set<string> } {
  const classSafelist = new Set<string>();
  const attrSafelist = new Set<string>();

  const componentUsages = new Map<string, PropUsage[]>();
  for (const usage of allUsages) {
    const existing = componentUsages.get(usage.component) ?? [];
    existing.push(usage);
    componentUsages.set(usage.component, existing);
  }

  for (const [entryName, entry] of Object.entries(manifest)) {
    const matchingUsages = findMatchingUsages(entryName, componentUsages);
    if (matchingUsages.length === 0) continue;

    for (const cls of entry.classes.always) classSafelist.add(cls);

    for (const [propOrSlot, value] of Object.entries(entry.classes.byProp)) {
      if (Array.isArray(value)) {
        if (isPropUsed(propOrSlot, matchingUsages)) {
          for (const cls of value) classSafelist.add(cls);
        }
      } else {
        const usedValues = getUsedEnumValues(propOrSlot, matchingUsages);
        if (usedValues === "ALL") {
          for (const classes of Object.values(value)) {
            for (const cls of classes) classSafelist.add(cls);
          }
        } else {
          for (const val of usedValues) {
            if (value[val]) {
              for (const cls of value[val]) classSafelist.add(cls);
            }
          }
        }
      }
    }

    if (entry.attrs) {
      for (const [propName, attrMap] of Object.entries(entry.attrs)) {
        if (isPropUsed(propName, matchingUsages)) {
          for (const [attr, val] of Object.entries(attrMap)) {
            attrSafelist.add(`[${attr}="${val}"]`);
          }
        }
      }
    }
  }

  return { classSafelist, attrSafelist };
}

function findMatchingUsages(entryName: string, usageMap: Map<string, PropUsage[]>): PropUsage[] {
  if (usageMap.has(entryName)) return usageMap.get(entryName)!;
  const results: PropUsage[] = [];
  for (const [usageName, usages] of usageMap) {
    if (usageName === entryName) {
      results.push(...usages);
    }
    if (entryName.includes(".")) {
      const [family, part] = entryName.split(".");
      if (part === family && usageName === family) {
        results.push(...usages);
      }
    }
  }
  return results;
}

function isPropUsed(propName: string, usages: PropUsage[]): boolean {
  for (const usage of usages) {
    if (usage.hasSpread) return true;
    if (usage.booleanProps.has(propName)) return true;
    if (usage.props.has(propName)) return true;
  }
  return false;
}

function getUsedEnumValues(slotName: string, usages: PropUsage[]): Set<string> | "ALL" {
  const values = new Set<string>();
  for (const usage of usages) {
    if (usage.hasSpread) return "ALL";
    const val = usage.props.get(slotName);
    if (val === "DYNAMIC") return "ALL";
    if (val !== undefined) values.add(val);
    if (usage.booleanProps.has(slotName)) return "ALL";
  }
  return values;
}

// ── Consumer source scanning ───────────────────────────────────────────────────

async function scanConsumerSource(srcDir: string): Promise<PropUsage[]> {
  const allUsages: PropUsage[] = [];
  const files = await fastGlob("**/*.{tsx,ts,jsx,js}", { cwd: srcDir, ignore: ["**/node_modules/**"] });

  for (const relPath of files) {
    const fullPath = path.join(srcDir, relPath);
    const code = await nodeReadFile(fullPath, "utf-8");
    if (!code.includes("@pathscale/ui")) continue;

    const isTsx = /\.[tj]sx$/.test(relPath);
    const ast = await swc.parse(code, { syntax: "typescript", tsx: isTsx });
    const uiImports = extractUIImports(ast);
    if (uiImports.size === 0) continue;

    allUsages.push(...extractJSXUsages(ast, uiImports));
  }

  return allUsages;
}

// ── Level 2: attribute purge ───────────────────────────────────────────────────

function purgeAttributes(css: string, attrSafelist: Set<string>): string {
  const root = postcss.parse(css);

  root.walkRules((rule) => {
    const selectors = rule.selectors;
    const kept: string[] = [];

    for (const sel of selectors) {
      const attrMatches = sel.matchAll(/\[(data-[a-z-]+|aria-[a-z-]+)="([^"]+)"\]/g);
      let shouldKeep = true;

      for (const match of attrMatches) {
        const attrSelector = `[${match[1]}="${match[2]}"]`;
        if (match[1] === "data-slot") continue;
        if (!attrSafelist.has(attrSelector)) {
          shouldKeep = false;
          break;
        }
      }

      if (shouldKeep) kept.push(sel);
    }

    if (kept.length === 0) {
      rule.remove();
    } else if (kept.length < selectors.length) {
      rule.selectors = kept;
    }
  });

  return root.toString();
}

// ── Level 3: unused CSS variable cleanup ───────────────────────────────────────

function cleanUnusedVars(css: string): string {
  let changed = true;
  let result = css;

  while (changed) {
    changed = false;
    const root = postcss.parse(result);

    const declared = new Map<string, { rule: Rule | AtRule; prop: string; index: number }[]>();
    root.walkDecls(/^--/, (decl) => {
      const entries = declared.get(decl.prop) ?? [];
      entries.push({ rule: decl.parent as Rule, prop: decl.prop, index: entries.length });
      declared.set(decl.prop, entries);
    });

    const referenced = new Set<string>();
    root.walkDecls((decl) => {
      const refs = decl.value.matchAll(/var\(\s*(--[a-zA-Z0-9_-]+)/g);
      for (const ref of refs) {
        referenced.add(ref[1]);
      }
    });

    for (const [varName, entries] of declared) {
      if (!referenced.has(varName)) {
        for (const entry of entries) {
          entry.rule.walkDecls(entry.prop, (decl) => {
            decl.remove();
            changed = true;
          });
        }
      }
    }

    root.walkRules((rule) => {
      if (rule.nodes && rule.nodes.length === 0) rule.remove();
    });
    root.walkAtRules((atRule) => {
      if (atRule.nodes && atRule.nodes.length === 0) atRule.remove();
    });

    result = root.toString();
  }

  return result;
}

// ── The rsbuild plugin ─────────────────────────────────────────────────────────

export const pluginCssPurge = (options: CssPurgeOptions): RsbuildPlugin => ({
  name: "plugin-css-purge",

  setup(api) {
    const {
      manifest: manifestPath,
      srcDir = "src",
      attrPurge = true,
      cleanVars = true,
      verbose = true,
    } = options;

    api.processAssets(
      { stage: "optimize-size" },
      async ({ assets, sources, compilation }) => {
        const log = verbose ? console.log.bind(console) : () => {};

        // 1. Load manifest
        const manifest: PurgeManifest = JSON.parse(
          await nodeReadFile(path.resolve(manifestPath), "utf-8"),
        );
        log(`[css-purge] Manifest loaded: ${Object.keys(manifest).length} entries`);

        // 2. Scan consumer source
        const resolvedSrc = path.resolve(srcDir);
        const usages = await scanConsumerSource(resolvedSrc);
        log(`[css-purge] Scanned ${resolvedSrc}: ${usages.length} component usages`);

        // 3. Build safelists
        const { classSafelist, attrSafelist } = buildSafelists(usages, manifest);
        log(`[css-purge] Safelist: ${classSafelist.size} classes, ${attrSafelist.size} attrs`);

        // 4. Process each CSS asset
        for (const [name, asset] of Object.entries(assets)) {
          if (!name.endsWith(".css")) continue;

          const originalCss = asset.source().toString();
          const originalSize = Buffer.byteLength(originalCss, "utf-8");
          log(`[css-purge] Processing ${name} (${(originalSize / 1024).toFixed(1)} KB)`);

          // Level 1: class-level purge
          const purgeResult = await new PurgeCSS().purge({
            content: [],
            css: [{ raw: originalCss }],
            safelist: [...classSafelist],
            keyframes: false,
            fontFace: false,
          });

          let purgedCss = purgeResult[0]?.css ?? originalCss;
          const afterL1 = Buffer.byteLength(purgedCss, "utf-8");
          log(`[css-purge]   L1 class purge: ${(originalSize / 1024).toFixed(1)} → ${(afterL1 / 1024).toFixed(1)} KB`);

          // Level 2: attribute-level purge
          if (attrPurge && attrSafelist.size > 0) {
            purgedCss = purgeAttributes(purgedCss, attrSafelist);
            const afterL2 = Buffer.byteLength(purgedCss, "utf-8");
            log(`[css-purge]   L2 attr purge: ${(afterL1 / 1024).toFixed(1)} → ${(afterL2 / 1024).toFixed(1)} KB`);
          }

          // Level 3: unused CSS variable cleanup
          if (cleanVars) {
            purgedCss = cleanUnusedVars(purgedCss);
            const afterL3 = Buffer.byteLength(purgedCss, "utf-8");
            log(`[css-purge]   L3 var cleanup: → ${(afterL3 / 1024).toFixed(1)} KB`);
          }

          const finalSize = Buffer.byteLength(purgedCss, "utf-8");
          log(`[css-purge]   Final: ${(originalSize / 1024).toFixed(1)} → ${(finalSize / 1024).toFixed(1)} KB (${((1 - finalSize / originalSize) * 100).toFixed(1)}% reduction)`);

          // Write back
          const source = new sources.RawSource(purgedCss);
          compilation.updateAsset(name, source);
        }
      },
    );
  },
});
